@startuml
hide footbox
participant SirDukeBox as ":SirDukeBox"
activate SirDukeBox
participant Ui as ":Ui"
participant Parser as ":Parser"

    SirDukeBox -> Ui : getUserInput
    activate Ui
    deactivate Ui
    SirDukeBox -> Parser : getCommand
    activate Parser
    Parser -> ":XYZCommand" ** : create
    activate ":XYZCommand"
    SirDukeBox <-- Parser : command object
    deactivate Parser
    SirDukeBox -> ":XYZCommand" : execute()
    ":XYZCommand" -> ":Flute" ** : create
    activate ":Flute"
    ":XYZCommand" -> ":InstrumentList" : addInstrument
    activate ":InstrumentList"
    deactivate ":InstrumentList"
    SirDukeBox -> Ui : print acknowledgment
    activate Ui
    deactivate Ui
    SirDukeBox -> ":XYZCommand" : isExit()
    SirDukeBox <-- ":XYZCommand" : false
    destroy ":XYZCommand"

@enduml